### ISSUE TITLE
WhatsApp2Html - Run problem

### ISSUE THREAD

**Issue by txanetxarra** [ITFLU/WhatsApp2Html#3]
Hello @ITFLU,

First of all, thank you for the development of the WhatsApp2Html script.

I've been trying to run the script, but i'm having some difficulties.

Just a couple questions:  Where should the script be run ? On the phone or in a PC ? and, Are there any dependencies to be installed in order to correctly execute the script?

I'm trying to run wa2h-cli.py using Python3 on a Windows 10 machine to convert a chat export from an Android WhatsApp.

Attached a capture of the execution of hte script.

> C:\Users\XXXXX\Desktop\WhatsApp_>python wa2h-cli.py --idate "%m/%d/%y, %I:%M %p" "WhatsApp Chat with YYYYY.txt"
> [i] Chat seems to be from iOS
> Traceback (most recent call last):
>   File "C:\Users\shane.malo\Desktop\WhatsApp_\wa2h-cli.py", line 519, in <module>
>     processed = read_chat(chatname, chat_format)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\shane.malo\Desktop\WhatsApp_\wa2h-cli.py", line 245, in read_chat
>     current_msg.add_to_message(line)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'add_to_message'
> 

Thank you in advance for your answer.

Best regards.

**Comment by crowd-ctrl** [comment]
Hi txanetxarra,

It seems to be a failure in the detection of the chat format (Android or iOS). Can you please send me the first one or two lines of your chat textfile (of course without the messages! only the beginning of the line until the beginning of the message...) to verify my suspicion and to check the planed fix.

**Comment by crowd-ctrl** [comment]
Hey txanetxarra,

it was the suspected problem. The new Release 1.1.3 should work...

Thanks for your notice!

**Comment by txanetxarra** [comment]
Hi @crowd-ctrl,

Nice.... I just testes v.1.1.3 and it's working now !!

Thank you so much.

Best regards.

😉👍
